"""add notification system fields to system_config

Revision ID: 3222502341d6
Revises: 12345678abcd
Create Date: 2025-09-16 23:28:04.910215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3222502341d6'
down_revision: Union[str, None] = '12345678abcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False, comment='通知類型：online_deal, achievement, system等'),
    sa.Column('notification_subtype', sa.String(length=50), nullable=False, comment='通知子類型：received_request, request_approved, request_rejected等'),
    sa.Column('related_resource_type', sa.String(length=50), nullable=True, comment='相關資源類型：online_deal, product等'),
    sa.Column('related_resource_id', sa.Integer(), nullable=True, comment='相關資源ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='通知標題'),
    sa.Column('message', sa.Text(), nullable=False, comment='通知內容'),
    sa.Column('extra_data', sa.Text(), nullable=True, comment='額外數據（JSON格式）'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已讀'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='已讀時間'),
    sa.Column('notification_shown', sa.Boolean(), nullable=False, comment='是否已顯示過通知'),
    sa.Column('shown_at', sa.DateTime(), nullable=True, comment='通知顯示時間'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_id'), 'user_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    
    # Add notification system columns to system_config
    op.add_column('system_config', sa.Column('notification_system_enabled', sa.Boolean(), nullable=True, comment='通知系統開關'))
    op.add_column('system_config', sa.Column('notification_cutoff_time', sa.DateTime(), nullable=True, comment='通知系統啟用時間，此時間之前的狀態變更不會產生通知'))
    
    # SQLite doesn't support ALTER COLUMN, so we skip these problematic operations:
    # - op.alter_column('comments', 'email', ...) 
    # - op.alter_column('system_config', 'online_deal_available', ...)
    # - op.alter_column('system_config', 'system_name', ...)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove notification system columns from system_config
    op.drop_column('system_config', 'notification_cutoff_time')
    op.drop_column('system_config', 'notification_system_enabled')
    
    # Drop user_notifications table
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    
    # SQLite doesn't support ALTER COLUMN, so we skip these problematic operations:
    # - op.alter_column('comments', 'email', ...)
    # - op.alter_column('system_config', 'online_deal_available', ...)
    # - op.alter_column('system_config', 'system_name', ...)
    # ### end Alembic commands ###
