"""Add system config table

Revision ID: a0357e010449
Revises: ace23ba84c0e
Create Date: 2025-08-10 19:45:02.068872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0357e010449'
down_revision: Union[str, None] = 'ace23ba84c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite 不支援 ALTER COLUMN，跳過此操作
    try:
        op.create_index(op.f('ix_comments_email'), 'comments', ['email'], unique=False)
    except:
        pass  # 如果索引已存在，忽略錯誤
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_email'), table_name='comments')
    op.alter_column('comments', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
