"""Add view_count to products

Revision ID: ff4e998ef5d5
Revises: a55a889069ad
Create Date: 2025-08-30 00:09:01.243533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4e998ef5d5'
down_revision: Union[str, None] = 'a55a889069ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 只保留添加 view_count 欄位的操作
    op.add_column('products', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 只保留移除 view_count 欄位的操作
    op.drop_column('products', 'view_count')
    # ### end Alembic commands ###
